# Generated by Django 5.0.3 on 2024-03-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('date_joined', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('qr_code', models.ImageField(blank=True, upload_to='employee_qrcodes')),
            ],
        ),
    ]
